---
title: "data_vis_training"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries, message = FALSE}
library(leaflet)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(scales)
source('ggplot.theme.original.R')
```

```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv"),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"))
        return(esc)
    }
)
# read from url but if not use a file you have saved on harddrive
```

Challenge: calculate annual escapement by species and region
```{r}
annual.esc <-  esc %>%
  separate(sampleDate, into = c('year','month','day'), sep = '-') %>%
  mutate(year = as.numeric(year)) %>%
  filter(Species %in% c('Chinook','Sockeye','Chum','Pink','Coho')) %>%
  group_by(year, SASAP.Region,Species) %>%
  summarise(annual_esc = sum(DailyCount))

```

Create tidy plot!
```{r create tidy plot}
ggplot(annual.esc, aes(x = year, y = annual_esc, color = Species)) +
  geom_point(position=position_dodge(1)) +
  geom_line(position=position_dodge(1)) +
  labs(y = 'Number of escaped salmon') +
  my.theme

ggplot(annual.esc %>% filter(Species == 'Sockeye'), aes(x = year, y = annual_esc)) +
  geom_point() +
  geom_line() +
  my.theme

# Other cool ggplot like packages
## ggmarginal for adding plots to your plot margins
## ggridges for density plots

```

# Leaflet Maps
```{r}
locs <- esc %>%
  distinct(Location, Latitude, Longitude) %>% # selects only unique rows from a dataframe.
  drop_na() # removes all NA rows. It is quite an aggressive function.

leaflet(locs) %>%
  addTiles() %>%
  addMarkers(lng = ~Longitude, lat = ~Latitude, popup = ~Location) # uses R model syntax
## HOLY COW THAT IS A MAP

leaflet(locs) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?", # this is the imagery tiles
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)
```

