---
title: "function_lesson"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Create Farenheit to Celsius function
```{r}
airtemps = c(212, 30.3, 78, 32)
FtoC = function(fahr) { 
  celsius <- (fahr-32) * (5/9)
  return(celsius)
}
# test the function
airtemps_C = FtoC(airtemps)
```

# Create Celsius to Farenheit function
```{r}
#` ROxygen makes the help page.
#` This function converts celsius values to Farenheit values.
CtoF <- function(celsius) {
  farenheit <- celsius * (9/5) +32
  return(farenheit)
}
# test the function
CtoF(airtemps_C)
# compare values
airtemps == CtoF(airtemps_C)
```

# Create function with multiple inputs
```{r}
mysum <- function(x,y) {
  return (x)
  return ("+")
  return (y)
  return ("+")
  return(x + y)
}
mysum(4,5)
```

# Complex return values 
```{r}
convert_temps <- function(fahr){
  celsius <- FtoC(fahr)
  kelvin <- celsius + 273.15
  return(data.frame(temp = c(fahr, celsius, kelvin), unit = c('fahrenheit', 'celsius', 'kelvin')))
}
# test the function
convert_temps(32)
temps.df <- data.frame(convert_temps(seq(-100, 100, 10)))
```

